"""unique participant per organization

Revision ID: 093196006778
Revises: 57418fd2735e
Create Date: 2026-07-31 14:48:41.960126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093196006778'
down_revision: Union[str, Sequence[str], None] = '57418fd2735e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_participant_org_name', 'participant', ['organization_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_participant_org_name', 'participant', type_='unique')
    # ### end Alembic commands ###
