"""add spans to speaker_cluster

Revision ID: 57418fd2735e
Revises: 0001
Create Date: 2026-07-31 13:54:06.965850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57418fd2735e'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: autogenerate also detected an unrelated stray table 'probe' in the
    # target DB (not part of any model); that drop was intentionally omitted
    # here as out of scope for this migration.
    op.add_column('speaker_cluster', sa.Column('spans', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('speaker_cluster', 'spans', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker_cluster', 'spans')
    # ### end Alembic commands ###
