"""add current_stage to meeting

Revision ID: c6171258c6ac
Revises: 093196006778
Create Date: 2026-07-31 15:33:57.363698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6171258c6ac'
down_revision: Union[str, Sequence[str], None] = '093196006778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('current_stage', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'current_stage')
    # ### end Alembic commands ###
