"""add meeting visibility and shares

Revision ID: f591adcdbe39
Revises: 9ff24f21aaeb
Create Date: 2026-07-31 19:29:04.008080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f591adcdbe39'
down_revision: Union[str, Sequence[str], None] = '9ff24f21aaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'account_id', name='uq_meeting_share')
    )
    op.add_column('meeting', sa.Column('owner_account_id', sa.Integer(), nullable=True))
    # Existing (pre-Phase-3) meetings have no owner and default to "private"
    # visibility; server_default backfills those rows so the column can be
    # NOT NULL.
    op.add_column(
        'meeting',
        sa.Column('visibility', sa.String(length=20), nullable=False, server_default='private'),
    )
    op.create_foreign_key(
        'fk_meeting_owner_account_id', 'meeting', 'account', ['owner_account_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_meeting_owner_account_id', 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'visibility')
    op.drop_column('meeting', 'owner_account_id')
    op.drop_table('meeting_share')
    # ### end Alembic commands ###
